# Generated by Django 3.2.4 on 2021-08-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Id', models.CharField(max_length=10, unique=True)),
                ('F_Name', models.CharField(max_length=15)),
                ('L_Name', models.CharField(max_length=15)),
                ('Birth_date', models.CharField(help_text='Date of Birth', max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Helpdesk_Support_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HDS_Id', models.CharField(max_length=10, unique=True)),
                ('F_Name', models.CharField(max_length=15)),
                ('L_Name', models.CharField(max_length=15)),
                ('Birth_date', models.CharField(help_text='Date of Birth', max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager_Id', models.CharField(max_length=10, unique=True)),
                ('F_Name', models.CharField(max_length=15)),
                ('L_Name', models.CharField(max_length=15)),
                ('Birth_date', models.CharField(help_text='Date of Birth', max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sup_Id', models.CharField(max_length=10, unique=True)),
                ('F_Name', models.CharField(max_length=15)),
                ('L_Name', models.CharField(max_length=15)),
                ('Birth_date', models.CharField(help_text='Date of Birth', max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.PositiveIntegerField(default=None, unique=True)),
                ('F_Name', models.CharField(max_length=15)),
                ('L_Name', models.CharField(max_length=15)),
                ('task', models.TextField(max_length=100)),
                ('feedback', models.CharField(max_length=10)),
            ],
        ),
    ]
