# Generated by Django 3.2.4 on 2021-08-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_task_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(max_length=15, unique=True)),
                ('F_Name', models.CharField(max_length=15)),
                ('L_Name', models.CharField(max_length=15)),
                ('Staff_Role', models.TextField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='No',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
